### ISSUE TITLE
motor.get() used incorrectly

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/RobotCode2021#23]
https://github.com/DeepBlueRobotics/RobotCode2021/blob/56de98b6965562b91dac4bca25820da5a20ec240/src/main/java/org/team199/robot2021/subsystems/Turret.java#L43-L52

seems to assume that `motor.get()` will return the speed that the motor is currently spinning, but that is not the case.

**Comment by CoolSpy3** [comment]
Actually, the code assumes that `motor.get()` returns the current setpoint of the motor. I've clarified this by renaming the `getSpeed()` function.

**Comment by brettle** [comment]
But for the purposes of trying to avoid the limits, do you want the setpoint or the actual speed that the turret is turning?

**Comment by CoolSpy3** [comment]
I think we would still want to use the setpoint. The code isn't designed to avoid the limits, but rather to confirm that the rest of the code isn't attempting to violate them. Both statements are just supposed to operate on the setpoint. The first does not care about whether the motor is turning, but rather whether the code is attempting to turn the motor. Likewise, the second statement doesn't care about how fast the motor is turning, but rather which direction the code is attempting to turn the motor. Because both statements don't care about the actual value of the result, but rather just its sign, the extra precision of an encoder is irrelevant.

**Comment by brettle** [comment]
Ok. I understand your intent now.
